const anita = `
<p>
Participant Transcript: Anita
</p>
<p>
Hello, I'm Anita and I am a playwright. I'm an instructional designer and also a garden designer. And I'm nearly fifty. I will be in three weeks. I never thought I'd get there. And proud to be here.
</p>
<p>
Sometimes I think home is somewhere I've never been. I've never been attached to places, even though I've lived in some places for quite a long time. I think home is a person, home is a state of mind, of a place of comfort that is with someone and the place doesn't matter. And that can be a group of people, too. I've lived in flat-shares that have been a great little family and a community and that's felt like home even though it was actually a shithole. And I've lived in a nice house with a ... that felt sterile and cold and I didn't want to be there. So home is not a place.
</p>
<p>
When I've tried to make a home, I've always tried to make a den. I like a small space. When I lived in a big house, I had a little den in the cupboard under the stairs. In this house, which is the closest I have to a home, my office is the smallest room. And when I was a child I used to like to make dens out of chairs and blankets and I like to retreat.
</p>
<p>
At the moment my office is a very accurate representation of my life in that there's loads of different project books. There's garden design plans, there are books that are half-read. There's a piles of paperwork and post-it notes and... It's not usually that chaotic but life seems to be just endless, small multitasking projects at the moment. Normally I like things to be quite neat. There's a wall of books of one side. Behind the desk there is another workspace which is a completely blank, white worktop which I keep clear apart from large plants at either end. And there's nothing on the walls apart from a Scrabble painting. The Scrabble painting is a, a 70cm by 70cm square made of Scrabble letters that were supposed to be arranged entirely randomly so they didn't make any actual words but accidentally words were made. I like its randomness.
</p>
<p>
I don't think my concept of home changed. I think I just realised that I was carrying it with me rather than it being attached to a physical building. And because the changes that were happening to me were in my body, it made sense that I had to move. So, it's the opposite way around for me than for many people who were diagnosed because I was diagnosed when I was very seriously ill and I was in hospital on a ventilator. And I had been ill for a long time before that without really realising, so my... My self was depleted, and when I was diagnosed and I was put on medication, my self started to come back to full strength and that destroyed my home. I no longer fitted in the space which I had created for myself. So, I left a relationship and a place and carried something new away.
</p>
<p>
I never felt excluded from anywhere because I was positive. Being diagnosed suddenly and, in my circumstances, kind of publicly because other people knew about my diagnosis before I did, because I was so ill they were coming to say goodbye, so... So, I had... People around me had to deal with the fact that I was positive before I knew it myself and then as soon as I was able to I had to kind of undo the panic and re-explain to people what this actually meant and this was the worse, the worse place it was going to be and I was going to be able to live and live well. So, I was fortunate in that I lived in a reasonably tolerant community. I was involved in theatre and I think theatre communities have always been quite welcoming of difference, so I didn't feel excluded there. I didn't consider that there was anything I shouldn't be doing or anywhere I shouldn't be going.
</p>
<p>
The doctors explained to my parents and my husband that I was HIV-positive and what that meant, but the ripple-out effect through my friends and family was kind of Chinese whispers, so... There's no non-sensational way to say Anita's dying of AIDS. It did cause a panic, it's a big word. Because the image is that that is not something you could ever recover from, when actually my body recovered extremely well and my viral load became undetectable very fast. My CD4 count rose and has remained stable to almost, almost normal-person level and that means that I'm no longer in danger. So these were things that I was only just understanding myself and I was having to sort of convey that to other people to undo the panic, because there's been very little education about HIV in the UK in between the tombstone/iceberg adverts of the ‘80s with John Hurt intoning “don't die of ignorance”, through to the present, unless you've been going through school years. And actually, through a block of the ‘80s thanks to Clause 28 there wasn't any education about gay sex. You'd have missed the messages, you'd have missed the messages of how to protect each other successfully, how to stop transmission and how to live with HIV healthily if you've got it. Those messages are still not clear.
</p>
<p>
Two positive experiences from living with HIV. And both of them have come through advocacy, actually, of, erm, being open about my status and speaking about it and trying to normalise it. One was when I spoke at the British HIV Association conference and I told my story and afterwards I got a standing ovation, and I didn't expect this to be an emotional moment for me. I've told my story before, but just to be inside the HIV-community and telling it and feeling an upwell of support around me, I was in tears. Yeah. I felt, I felt like I was literally supported in this bubble of hope and care. And another was just I've been mentoring people with HIV and I was with one person who had a journey that involved recent diagnosis and managing alcohol addiction at the same time and we went on a four-or-five month journey and that person came out the other side. That person came out of the mentoring experience having successfully completed rehab, having seen a way forward with HIV and feeling able to have a relationship in the future to being able to see grandchildren, to starting to take tentative steps towards retraining and getting work, and I've never been more proud of a person than I was when they came out of the other side of that.
</p>
<p>
Generally speaking, I've been quite open about my status from the beginning and... but I have occasionally encountered stigma. One was a friend of my husband's. His wife wouldn't let me stay overnight in their house in case I gave HIV to the children, or was in some way a bad influence. I don't understand where her fear came from, but I didn't feel welcome and nor did I wish to be around her, actually.
</p>
<p>
I've received stigma in healthcare services. I joined a new dental practice and told them I was HIV-positive and when I went to meet the dentist he was covered from head-to-toe in plastic, I could barely see his eyes. He refused to shake my hand and he looked scared. He basically said: “I can look at your teeth but I can't do any procedures on you, we don't have the decontamination facilities here.” At which point I said to him: “Well, I'm going to report you to your governing body because if you cannot protect your other patients from my HIV, you certainly cannot protect anybody here from hepatitis, flu, even the common cold and I wrote the right letters to the right places and he got retrained.
</p>
<p>
Oh and I had to have that whole conversation with the door open with me standing on the threshold of the waiting room, discussing my HIV-status in front of receptionists and everyone else who is wanting to listen. I wonder if any of them had the blood-borne viruses conversation and thought twice about being treated. I hope so. I self-stigmatise myself, as well. In a rash moment, I decided to join a karate class just because it was around the corner and it was kind of interesting and even though we weren't sparring with each other, just because I was just a complete beginner, I looked at this space and thought: ‘I know that my viral load is undetectable and I am untransmittable but I actually don't want to have to explain that to people here. And I don't want to alarm anyone.' So I walked out. I did self-stigmatise in that moment. I would have been useless at karate anyway, I'm a complete wimp.
</p>
<p>
My diagnosis was immensely traumatic for everyone who was around me, because I was so so ill. It was horrific and I wish I could have spared the people around me that experience. It was... It was not only difficult news, the whole thing was visceral and... It was a, it was a horror movie. So erm... There's so many stops along the way where that could have been prevented, including... Is that a dog? I might just bring him in. I've no idea what you're going to get here. Ratty, let's have you over here. Tuck in.
</p>
<p>
I think because I was so ill and it was... and my diagnosis was late, and it was traumatic and I was in hospital and I was dying, it was a nightmare. It was a nightmare for everyone around me. It was... It was really traumatic and I would have dearly loved to have spared everybody that experience. Everyone was incredibly supportive at the time and they were on my side and willing me through it, praying, singing folk songs, reading me, to me from Hello! magazine, whatever it was that they felt they could do to get me through. So I haven't felt judged but people see me as fragile in a way that they perhaps didn't before, and it's taken me quite a long time to reassure people that that's not going to happen again, I'm okay. Really, I am okay.
</p>
<p>
I think a safe space is always to do with the close friendships I have around me. My husband but also my female friends and old friends. It's also a mental space, which is... It's the same place that I retreat to when I'm creating. Which is part-medative... Which is partly meditative but it's also moving elements around at very high speed. Kind of trying different arrangements of story, thought, character, plants. Whatever it is I happen to be working on. And I can move myself into that space from actually quite emotional spaces or quite stressful spaces. I can even drop into it for a fragment of time. Thank you Ratty. As a writer I've kind of trained myself to drop into that space and use it quite effectively even if it's for a short duration.
</p>
<p>
I think my first community is the household community, which is partly being part of a dog-pack actually. That community is quite vocal at the moment, thank you Ratty. That community has brought me into the community into which I live, because I'm constantly, sort of, trying to find new walks and new footpaths and we're bumping into people and we get to know the landscape and the seasons. The dogs have really placed me in this place. So in some ways I think I have a better connection to where I am now than anywhere I've been, ‘cause of these critters. My other communities are kind of more virtual. I have the, I have my community of people I make radio with. I have my community of people... I have my community of people I make learning products with. The other community that I am connected with is the HIV-community and that's something that's only happened in the last two or three years, where I've been, become a mentor with the Sussex Beacon, I've become a speaker with Terrence Higgins' Positive Voices because I want to tell this story about ‘can't pass it on'. I want to tell this story about ‘we live well'. I also want to tell this story about ‘we can end transmission', the 2030 target the Government has said and that people don't need to live with stigma and trauma. They don't need to live with ill health. But when people with HIV encounter these problems along the way, there's a community out there that can help you through it.
</p>
<p>
Describing myself? My favourite animal is the armadillo, which if you've never met an armadillo, they're actually quite bold. They wander around poking their nose into things. They can be quite loud, a little bit clumsy. They're a little bit secretive because they're nocturnal, but the important thing is they kind of carry their own shell. They carry their own home. So in a minute's notice they can curl up into a ball and they're completely self-protected. So I think of myself as a bit of an armadillo.
</p>
<p>
I also, I'm also going to throw this one in, it's not a question, but I also see myself as a home. I am a habitat, I am a biosphere and I carry, as everyone does, a raft of little microbes, viruses, bacteria, fungi, other things that make eggs, things I don't have names for. And among them is the HIV virus. So, like it or not, I am a home.
</p>
<p>
I'm planning my 50th birthday party at the moment and I've probably been living with the virus for 25 years, so I think that kind of makes it a sort of silver wedding. It's the longest relationship I've had with any organic being and - please try not to be so bored, Ratty - and... I'll start that again. It was a bit shit, anyway. I'm going to be 50 this year and I've been living with the virus for 25 years, which is a kind of silver anniversary. It's a very long-term relationship and we're both kind of dependent on each other. One could say we're toxically co-dependent but - like it or not - here we are; we're bonded. And it's the end of the line for the virus because I'm not going to pass it on. Also weirdly it's the end of the line for me because in my 30s I decided I was not going to have children, because I was HIV-positive. With different information a different person might have made a different decision, but anyway... So. I am planning my birthday party and we're both going to have a cake. I'm going to have a cake and so is the virus and it will be very interesting to see if any of my friends eat the virus cake.
</p>
<p>
My cake is going to be vanilla sponge. I might layer it up to look a bit like an armadillo and the virus cake is going to be the chocolate cake which is the one that everyone's going to want to eat. It'll be covered in green icing and spiky bits. I don't know if it's even possible, I can't bake a cake. I can't even bake a potato.
</p>
`;

module.exports = anita;
