const jose = `
<p>
  Hi, I&rsquo;m Jos&eacute; Mejia. I&rsquo;m a brown, gay man from Colombia, hence my accent. And I, yeah&hellip; I work, love, enjoy, live, dance, not very good but I do, and that&rsquo;s it.
</p>
<p>
  When I think of home I get, like, a cosy feeling, that&rsquo;s kind of the first thing that happens. I need to have that comfort. That&rsquo;s the first thing that comes to my mind, that comfort, calm, etc. It&rsquo;s just, home has always been like my safe space. Yeah, I think, I think as a gay man it was a place where I used to hide but also protect myself I guess. Yeah, as a young gay man from being bullied at school and things like that, so home was always like a safe space for me and the same happened for me then later on in life with my HIV-diagnosis, the same. It was where I used to hide and be myself and process things. It&rsquo;s a place where I process, where I explore, where I sort of find myself. Yeah, and then more in terms of visually I think green, I like plants a lot, so I like it to be green and airy. I like the windows open and so, so, that&rsquo;s why I struggle in the winter when I just feel like I&rsquo;m trapped and there&rsquo;s no air flowing, and&hellip; But yeah, what else? Yeah, I think it&rsquo;s where I can be with myself but where I can also host people and invite people over and feel comfortable with people around and yeah, it&rsquo;s just a space where I feel comfortable I think.
</p>
<p>
  So I think in order to feel at home I need like&hellip; Quietness, like I, yeah... I tend, my space tends to be very quiet. I play music but in many other times I&rsquo;m just in, like, complete silence and I quite like it. I think that&rsquo;s one of the things I need to feel at home. I need to feel loved to feel at home, so I feel at home here in my house. I feel at home in my Mum&rsquo;s house. I feel at home, in my partner&rsquo;s house, I feel at home, yeah, in my dad&rsquo;s house, in my sister&rsquo;s house, where I feel loved, I think that&rsquo;s one thing that makes me feel at home and&hellip; Yeah.
</p>
<p>
  So&hellip; Yes, so it&rsquo;s a small studio flat, a square-shaped studio flat with a really nice floor-to-ceiling window, wall-to-wall, so a really nice view of the city. That makes the space really bright, which I really like. You can see the view is really nice, you can see bits and pieces of Parliament and the, like, the London Eye and some few landmarks of the city. It&rsquo;s full of plants, there&rsquo;s a lot of plants. There&rsquo;s, like, different sorts of frames with pictures that I&rsquo;ve got from different places, travelling, or from magazines and things, stuff like that. Yeah, it seems like a &lsquo;70s sort of flat and then yeah I think it&rsquo;s very smart in terms of it&rsquo;s a small space but it has all I need. I have my bed, it has a little sofa, it has my desk where I&rsquo;m working at the moment because I&rsquo;m working from home. There&rsquo;s a nice kitchen, a nice bathroom so yeah, it seems to have everything that I need. There&rsquo;s also a lot going on because I have a lot of stuff, like things, a lot of clothes, a lot of, like, crap I guess, like things. So yeah, there&rsquo;s a lot going on but I try not to worry too much and I do my spring-clean every so often so there is more space. But it feels&hellip; Yeah, I don&rsquo;t know. It feels vibrant and alive a little bit.
</p>
<p>
  Yeah, I think my perception of home might have changed after my diagnosis. I&rsquo;m trying to think how. I&rsquo;m sure it did. I think, as I said before, I think partly, yeah, my diagnosis made me go more inwards and in that process of going inwards, whether it was, for good, for good and for bad, because a lot of it was good, it was a process of reflection which brought many benefits, but it was also a process of isolating myself which brought some not very good things. So in that process of going inwards and going more to myself and hiding and like sort of sheltering a lot, well home was really that space where I could do that, you know, where I didn&rsquo;t have to face the outside, where I didn&rsquo;t have to face other people, where I didn&rsquo;t have to face the reality of what was happening and the things that I was living. So, yes, I used to go to the clinic and I use to hate it and I used to come back home and it was that space where I could just cry and cringe and hate and be annoyed with myself and be annoyed with the world, without needing&hellip; Yeah, without needing to put that mask on, or put that face on, or that smile and just know I could be myself and that was what I did at home was process and reflect at what was going on. So, yeah, I think it did. I think probably before the diagnosis it was more of a little bit of a party place, I guess. I was young, I was very young so I was still very social and stuff and then after the diagnosis it became more of my sort of temple rather than a party-place, yeah of course. Then with the years and moving forward and those things and I got to a better place &ndash; well, I still make parties and I still invite people and I all of that &ndash; but yeah, home became more of a temple for myself and my body and my mind to be honest.
</p>
<p>
  So I think a positive reaction to know that I was living with HIV&hellip; I mean, I think they didn&rsquo;t happen very quickly. I think it took me many years to find the positive things of living with HIV. I now, on reflection, can say that a lot of things are positive, like my lifestyle has changed for the better. Yeah, I think I feel medically more looked after than a lot of people. I think the one thing that I knew from the very beginning &ndash; and it just wasn&rsquo;t the right time then &ndash; is that I wanted to work on the area, that I wanted to learn more and I wanted to do something about this. And I verbalised it to the first doctor that treated me and he said: &ldquo;That&rsquo;s great, keep that in mind, just keep that in mind.&rdquo; And I did that, I hold onto that thought and that happened many years later.
</p>
<p>
  So I think the other positive thing is that it has given me a career, a professional thing to do, at least for a few years in London. And I think the other great, well, the other two things that I find great is that it has made me a resilient person. I feel much more resilient than I used to be, I feel now that I can face anything. I think that I have gone through very dark things and the whole process was very difficult and it has just made me stronger, I think. And the other thing is the sense of community. You know, I firmly believe that I belong to a wide and diverse community of people living with HIV and whether I know those people or not I feel a part of that community and I felt welcome and I felt embraced and I felt nurtured and I feel looked after. And I try to do the same with others because I feel a part of that, so yeah; I think that&rsquo;s been the nicest thing from the whole thing.
</p>
<p>
  The community of people living with HIV is a safe space. It is for me. Yes, I&rsquo;ve always felt protected and I think I&hellip; When I think&hellip; I mean, I&rsquo;m not saying there&rsquo;s&hellip; There might be mistakes and we might think as a community that we do wrong and there might be things which as a community that we disagree on, and we don&rsquo;t agree with one other and&hellip; So, I just don&rsquo;t want the fact that I feel it&rsquo;s a community doesn&rsquo;t mean that it&rsquo;s just cohesive and perfect and all of that, it&rsquo;s&hellip; As any other community: complex, complicated and&hellip; But, I feel safe. I feel that we are looking after one another. I feel that&hellip; Yeah. And I think I felt very well- &hellip; Since I started, it was feeling that process of belonging to a community that would make me feel even more comfortable talking about my diagnosis, so&hellip; It was first realising that there was a community that I could tap into and then realising that I could be vocal within that community and I could share my story within that community and that my story was going to be welcome and that my story was going to be, yeah, just appreciated. I mean, embraced for whatever reasons, so yeah, I think I feel safe.
</p>
<p>
  I&rsquo;ve had many negative reactions. I mean, not many and then like if you think in perspective I&rsquo;ve heard of others that are even worse so I mean&hellip; It&rsquo;s hard to say because I don&rsquo;t wanna minimise it but I don&rsquo;t want to exaggerate it either so&hellip; It&rsquo;s just been&hellip; There is negative reactions, or let&rsquo;s say it&rsquo;s not right to phrase it in negative and positive things. There&rsquo;s been challenging situations that I&rsquo;ve faced as someone with HIV, within my own family and the closest, yeah, my, closest family. No&hellip; Partly because of a lack of information and a lack of awareness and at that time my lack of awareness. So, it was really, so, we did a process together of learning about the condition and learning about the things that I was going to go through and learning about my medical, sort of, treatment and so it was a process that I did very closely with my family, of course, with separation and with reservation. I did my part, they did theirs. But it was a joint sort of work, let&rsquo;s say, and I am very fortunate of that, but that came with some initial, yeah, uncomfortable and challenging situations and conversations.
</p>
<p>
  I&rsquo;ve had negative experiences dating and with other gay men. I&rsquo;ve been stigmatised by and, or discriminated by other gay men. There&rsquo;s been assumptions of the type of person that I am, the type of sex that I have, the type of behaviours that I engage in. Some of them right, some of them wrong. There&rsquo;s been, yeah, rejection and guys telling me they&rsquo;re not interested in having sex or dating someone living with HIV, like myself. So yeah, all of that&rsquo;s been negative but even within that I&rsquo;ve, like, yeah, the latest thing to happen not very long ago is that I had, like, a situation in which I was rejected or discriminated online and then probably a year later the guy came back and apologised and that was nice to experience as well and it was an opportunity to have an open and honest conversation about the whole situation but then there is&hellip; Yeah.
</p>
<p>
  Yeah, I really appreciated, it was very&hellip; It talked a lot about him, you know, it was like I was very shocked when the whole challenging moment happened because it was bad and I heard things that I didn&rsquo;t need to hear and that weren&rsquo;t fair or okay. I, in those situations, I don&rsquo;t stay quiet, I don&rsquo;t just&hellip;. Yeah, if I get annoyed I&rsquo;ll express how annoyed I am and if I get sad I&rsquo;ll show how sad I am and, so I don&rsquo;t hold my emotions I guess. But I also don&rsquo;t feel that I have to change anyone&rsquo;s mind or that I have to change anyone&rsquo;s perception because I don&rsquo;t, because that&rsquo;s their problem and their process and I don&rsquo;t mind and I don&rsquo;t need to convince anyone about anything. I know where I&rsquo;m standing. But, yeah, so when it happens, knowing that that happened without me having to be that person was quite nice and that he took- &hellip; Because he didn&rsquo;t have to. He could have learned and changed his attitude or knowledge or behaviour but he could have not say anything to me but he came and with each other that was quite nice.
</p>
<p>
  I think, my HIV-diagnosis have, in a positive way, affected my closest relationships. I think with my family, well, my family and in my closest family, with my Mum, my Dad, my sister, like, they all know, they&rsquo;re all supportive or they&rsquo;ve all been supportive throughout the process when I was within my darkest sort-of place and now that I&rsquo;m in my brightest, sort-of, moment with the whole thing, they&rsquo;ve been very supportive. They&rsquo;re very supportive of the work that I do as well, so that&rsquo;s also really nice. But I think in general terms it just brought us closer, you know, it was&hellip; Yeah, it was just a process of getting to know each other better and getting to know what we &ndash; ...and yeah, they didn&rsquo;t have to either, they, like many other families do they could have just not engage or not care or rejected me, because you hear those stories, but they didn&rsquo;t and they did their part in learning and educating themselves and I did the same so, yeah, I think the whole thing brought us together and we now have a much more honest and open relationship because of that. Yeah, and it was interesting because I think it was also being gay it was a sort of two-way process and I&rsquo;m not saying they&rsquo;re the same but I came out as being gay and then I came out as living with HIV, those two processes and for them it was like a realisation of just how honest I am, I&rsquo;m just not good at hiding things. I just can&rsquo;t live with secrets, that&rsquo;s not my thing. So, I just didn&rsquo;t do it, I decided not to do it and I think that was appreciated and that sort of&hellip; we built it from there.
</p>
<p>
  And I think with my partners, with my exes, I have a little collection of exes &ndash; no, I&rsquo; m joking &ndash; but I have a few exes and I think&hellip; Yeah, with my exes it&rsquo;s the same. There have been challenging moments or there was challenging moments with some of them but again, it was another bridge we crossed in the relationship and it&rsquo;s been fine. I think it has also helped me build healthier&hellip; My latest, sort of, relationships or my newest boyfriend, it&rsquo;s a healthier relationship because there was that level of honesty and openness from the very beginning and I think that helps, yeah, building trust and building rapport and getting to know each other quicker and in a more open way, so, I think&hellip; It has helped with my friends. I think I wouldn&rsquo;t be here if it wasn&rsquo;t for a very small group of friends that I used to have in Colombia who were the only ones I used to share things with in the very beginning and they just stick by my side, like, I get emotional and everything when I talk about it but they stick by my side and when I say: &ldquo;I don&rsquo;t want to do anything, I&rsquo;m just going to stay at home, I&rsquo;m not going to the party, I&rsquo;m not doing anything,&rdquo; and they were there like: &ldquo;Come with us, come with us, we&rsquo;re gonna pick you up, we getting there, you&rsquo;re coming to us, we&rsquo;ll see you here, come, come, don&rsquo;t stay, come, do something.&rdquo; And, like, yeah, it was annoying many times and it was difficult for me, at times I hated the idea of them knowing what I was going through but if it wasn&rsquo;t for them I wouldn&rsquo;t be here. They just hold me so much and they just hold the space for me so much and they just pick me up when I was down and they were just supportive and there all the time and, again, those were the relationships where I think I&rsquo;m probably still very close, well very close in the distance I guess, but very close I had with all of them, I don&rsquo;t talk often with all of them but it&rsquo;s memories that I will always, sort of, cherish and my perception is they feel proud of how far I&rsquo;ve come and of what I&rsquo;ve done in terms of just my own life, just, just moving from that very dark place in which I was, at some point.
</p>
<p>
  If I&rsquo;m asked to describe myself I would first ask if they wanted to know about me, how I look, or what I&rsquo;m made of, if that makes sense. Yeah, because I can describe what I look like and that might be easier than, than, actually, yeah, who I am. So it depends.
</p>
<p>
  So physically I&rsquo;m not too tall, I&rsquo;m brown-skinned, I have, like, big bushy eyebrows. Yeah, I think I have a nice smile that I don&rsquo;t use very often or that I use sometimes cheekily. I have, at the moment, kind of short dark hair but it kind of grows sort of, yeah, sort of different lengths. I&rsquo;ve lately gained some weight so I&rsquo;m looking a bit bigger than I use to but I&rsquo;m sort of liking it actually and yeah, I&rsquo;m just like, not thin, not big, just, yeah. Normal sort of complex. Yeah and my eyes are, my eyes and my hair are black so that&rsquo;s kind of what I look like.
</p>
<p>
  And then who I am and how I would describe myself, I think I&rsquo;m&hellip; I think I&rsquo;m a caring person. I think I&rsquo;m very, sort of, passionate about things, for good and for bad. That passion sometimes drives me into action, sometimes it drives me into inaction. I just get so overwhelmed that there is not much I can do, yeah, I just don&rsquo;t know where to start. I think I&rsquo;m a mix of, like, being like, being very gentle but very rough. I can be very rough with my eyes or with my hands or with how I talk sometimes but I&rsquo;m very gentle at heart and I don&rsquo;t mean any&hellip; Well, yeah sometimes I get angry as well, but I think that&rsquo;s the other thing I would say I don&rsquo;t know how to hide my emotions, like you will know, you&rsquo;ll know what&rsquo;s happening. You&rsquo;ll know&hellip; Yeah, you&rsquo;ll be able to see how I&rsquo;m feeling somehow. Either because I&rsquo;m trying to hide it and I&rsquo;m not very good at it or because I&rsquo;m not trying to hide it and I definitely will tell you how I&rsquo;m feeling. So I think I&rsquo;m very honest as well. I think I&rsquo;m very impatient or I can be very impatient at times. And&hellip; I&rsquo;ve sort of allowed myself to be vulnerable in many situations or scenarios all through my life and that by association and that has come with other things as well, throughout, as an example, yeah, at times feel shamed or ashamed or both. And I feel calmer than I&rsquo;ve felt before and, like, more at peace with myself that I&rsquo;ve felt before. And that feels like quite an achievement from my youthness in which I just didn&rsquo;t know what the hell was going on. So, yeah...
</p>
<p>
  I think there&rsquo;s just two things that I would like to add. I mean, is one don&rsquo;t, don&rsquo;t... One be kind, like, to yourself, to others. Two, like, sort of don&rsquo;t judge a book by its cover and just like, yeah. What you see is not always what you get and I think there&rsquo;s many layers to all of us, so, so dig deeper into all those layers. Well, with myself and with people again don&rsquo;t judge me by these words or by these photos because there might be much more than this, that you might like or not but there&rsquo;s more. And there&rsquo;s always more in people and I think that&rsquo;s, kind of, yeah&hellip; Important.
</p>
`;

module.exports = jose;
