const joshua = `
<p>
My name is Josh, I&rsquo;m from Swindon and I live with HIV.
</p>
<p>
When I think of home, I feel it&rsquo;s a comfortable place. Hopefully, a stylish place. It means acceptance, doing the things I want to do, no judgement, safety, comfort&hellip; Support. Family. Whatever that means. I feel at home with my family, mainly. Whether that&rsquo;s in the UK, or Hong Kong, or New Zealand. I like to talk, I like to feel like I&rsquo;m emotionally intelligent. So, I think that being able to talk about my feelings, especially with my family, that makes me feel I&rsquo;m home. To talk about difficult subjects with them and to get support from them on the difficulties of life. That for me is when I&rsquo;m at home, whether that would be at one of my parent&rsquo;s houses or in my brother&rsquo;s flat in Hong Kong or my brother&rsquo;s house in New Zealand or in my own home with whoever it is, could be some of my best friends or with my family members.
</p>
<p>
So my home is a little bit edgy, maybe. Have wooden floors, dark grey walls. I like to think I have a little bit of an eye for design or trying something a bit different. But also, for it to be comfortable and lived in to&hellip; Be a nice place to go, to wake up in the morning and come downstairs and be able to enjoy nice things in life, nice food, nice wine with friends, or a partner.
</p>
<p>
In my home I always try and have nice smells, so I burn incense. I have a lot of reed diffusers. I buy lovely smelly candles, like Russian leather candles. I love Ood as it&rsquo;s a woody smell. A lot of the smells I try and add to my home are Ood-based. For me, music is a big part of what makes a home so in every room of the house I have a speaker. I even have a speaker that I take with me all around the house to listen to music on. I love that, I love to hear chilled music, relaxing music, Classic FM and then also some more faster dance music, drum-n-bass, things like that. So I always have like a strong connection to music in my home.
</p>
<p>
My perception of what home was historically had always been my family home, which I lived in until I was early-20s and that&rsquo;s where I told my Mum about my HIV. Very, very shortly after I was diagnosed, so I told her on the Sunday after being diagnosed on the Friday. I was living with my brother and his wife at the time in London and they were my rocks, like, they were so supportive and I told them on the Sunday night, I think it was. So I told my Mum in the day and I told my brother and his wife in the evening. And that was just this flat in London, so that flat will always remain as the place in which I told them of my diagnosis. It wasn&rsquo;t&hellip; It was our home but it wasn&rsquo;t a home for very long. It was a home for a year. It wasn&rsquo;t something that we&rsquo;ve then taken with us and it&rsquo;s not remained a constant in my life. The family home was a constant, but now it looks like it won&rsquo;t be a constant as life develops and parents separate and things. And now my perception of a home is my own home, the space that is mine and that I&rsquo;ve kind of built on over the last three years.
</p>
<p>
So, a strong positive experience for telling someone that I have HIV would be one of my partners in like the last couple of years. Telling people you have HIV when it comes to the romantic sense or a sexual relationship can always be fraught with challenging conversations or rejection or whatever it is and I&rsquo;ve had it a couple of times where I would tell a guy and he would just be like: &ldquo;Okay, cool. Let&rsquo;s get on with it. Let&rsquo;s carry on as we were.&rdquo; That sort of thing. And I love that as a positive response because it is what it should be. It&rsquo;s just another thing and it doesn&rsquo;t impact anything in the relationship. It may be something that you might have to consider at some point, but mainly &lsquo;Oh, have you seen my pill box?&rsquo; or &lsquo;Have you seen where my pills are?&rsquo; Not anything like that should be judged or have some morality attributed to it. The strong negative reaction is also similar. The strong negative reaction is usually: &ldquo;Oh, thank you, like, for telling me, like, that you have HIV. I dodged a bullet there.&rdquo; As if me telling someone that I live with HIV... I&rsquo;ve saved them from getting HIV when we know now that the science is clear and me taking my medication means I&rsquo;m undetectable and it means that I can&rsquo;t pass it on to anyone even if I have unprotected sex with them. So for these people that I&rsquo;ve met where I&rsquo;ve had very strong negative responses, when I&rsquo;ve told them about my HIV, they&rsquo;re just in this land of ignorance, of fear, of a virus which is actually, it&rsquo;s managed now and they don&rsquo;t need to worry about those things and I feel like they&rsquo;ll continue to live in this negative world of denial of what HIV is and what it isn&rsquo;t and&hellip; It was difficult to go through that especially in the early days of being HIV-positive because that was when I needed to be accepted the most and it was when I was rejected the most. And now I&rsquo;m myself and comfortable with myself and comfortable with my HIV-status and I don&rsquo;t need anyone&rsquo;s approval, disapproval or anything and that&rsquo;s when I finding the most acceptance.
</p>
<p>
So I guess as a gay man it&rsquo;s not like I feel I&rsquo;m in a space when I&rsquo;m on Grinder or a dating app, but with gay bars closing down and gay clubs closing down we don&rsquo;t really have a space that we really mix in and it seems to be all online and I&rsquo;ve definitely felt excluded from those spaces when I&rsquo;ve put my status on my profile, because people wouldn&rsquo;t respond to your message or people would say &lsquo;no thanks&rsquo; and some people would say, explicitly, like: &lsquo;No thanks, you&rsquo;ve got HIV.&rsquo; Or not even &lsquo;no thanks&rsquo;, they would just say the most horrific things to you and in those ways you do feel rejected in a space where you felt like you could meet other people and potentially other people like you and all they&rsquo;ve done is narrow in on an attribute on your profile and then they&rsquo;ve rejected you based on that which is incredibly ignorant anyway but&hellip; And also you would go through the second-guessing yourself of &lsquo;maybe this person didn&rsquo;t reply because they can see my HIV-status,&rsquo; so then you take it off your profile because you think people will message you more. And sometimes they do. Or people would forget you were the person who had HIV the last time you were online and so now they reply to you.
</p>
<p>
I would say HIV hasn&rsquo;t affected my living situation. I was flatting with friends and ex-colleagues at various points when I was living in London and it wasn&rsquo;t an issue. They knew that I had HIV. I had told them about it. I came out quite publicly at work. I told people at work about it so working with these people and then living with them it wasn&rsquo;t, it wasn&rsquo;t an issue at any point but I could understand how it might if you haven&rsquo;t been as open as I was that, even hiding your medication or anything like that, of a very practical nature, how it can affect your living situation.
</p>
<p>
HIV did affect my closest relationships, not in a way that it destroyed them or they stopped being my closest relationships generally. It actually brought me closer to a lot of my friends. People responded in really strange ways like going from thinking I was going to die to having this more admiration and respect for me as a person because of the hardship I&rsquo;ve been through. Some people, like, it wouldn&rsquo;t be a good thing, it wouldn&rsquo;t be a bad thing, it would just be another thing to the relationship and that&rsquo;s totally fine as well but I definitely felt closer to a lot of my friends after I told them, and continue to feel close to those people because of the, kind of the shared trauma because they were with me when I was in the thick of it when it was really challenging for me and they&rsquo;re with me today as some of my best friends still.
</p>
<p>
I would say that I&rsquo;m part of the HIV-community. Through volunteer work in London and in Swindon. We create this weird network of people and the one thing that we have in common is that we all have HIV. I remember being in a pub in London where someone was looking at our group of mismatch people; disabled, abled, young, old, men&hellip; It was a gay men&rsquo;s HIV group, and they were like: &ldquo;We&rsquo;re trying to work out how you guys all know each other.&rdquo; And we were like: &ldquo;Well, we&rsquo;re all gay so that&rsquo;s why we&rsquo;re all here together.&rdquo; And they were really confused by the answer. But it was a total mismatch group. It was so diverse and we had all races, all abilities, young and old, and we were all there because we all had this shared thing that for a lot of us it was traumatic and, but we were dealing with it, we were meeting others like us and coming together to create a community and that&rsquo;s like one of the biggest things that I&rsquo;ve got out of being HIV-positive is that sense of community and sense of belonging and in some ways I wouldn&rsquo;t change my HIV-status because it&rsquo;s given me so much more in life than I had before I was diagnosed with HIV.
</p>
<p>
I feel quite safe wherever I go. I don&rsquo;t know if I have a safe space. I feel like I can live quite openly, quite authentically, so I don&rsquo;t necessarily have a need for a safe space, or, if I do then I know where I need to go to get it and that would be with some close friends or family. I feel like I can be myself and be myself in front of strangers as well which is quite a powerful thing to do, especially with regards to my HIV.
</p>
<p>
I would describe myself as, I guess, passionate, thoughtful and kind. I would hope that me as a person that I can challenge people, but hopefully with a smile on my face. Hopefully get people to think in different ways, not to kind of accept the world that they see and live in but to get to a closer understanding of what that reality really is, to hopefully talk about things, the challenges in life. So I would describe myself as someone who can hopefully bring that out in people, does that answer? I don&rsquo;t know.
</p>
<p>
I guess the key for me is, if I could speak to an audience who are from all walks of life who don&rsquo;t necessarily have exposure to people with HIV, they don&rsquo;t understand it, they&rsquo;re scared of it like I was scared of it, so they don&rsquo;t engage with it, what would I say to those people? And I would say that people who live on&hellip; I would say that people who live with HIV, who are on treatment, who have an undetectable viral load are basically HIV-neutral. They&rsquo;re not HIV-positive, they can&rsquo;t infect you with HIV. That is the biggest learning that everyone in the world needs to understand because that&rsquo;s like the biggest step to removing stigma from people who live with HIV and it can help people to understand that when someone tells them they have HIV that they&rsquo;ll know that they&rsquo;ll live a long live and they&rsquo;ll be healthy and they&rsquo;ll be looked after and they&rsquo;re not going to be infectious to anyone.
</p>
<p>
I guess, for me, I felt like it couldn&rsquo;t happen to me and through my own ignorance and where I was at, it did. So I think that that&rsquo;s something that people need to be aware of. It&rsquo;s the same with other viruses that we&rsquo;re seeing today. You go to a house party, &lsquo;it wouldn&rsquo;t happen to me&rsquo;, but it does.
</p>
<p>
So one of the questions that people on Grinder when they don&rsquo;t really know what HIV is, one of the questions they feel entitled to ask you is: &lsquo;How did you get it?&rsquo; And if I was to be really honest about the reason why I got it, it was because I didn&rsquo;t have respect for myself. I was in a place where I didn&rsquo;t really like myself. And not that I sought it out and not that I was engaging in risky practices, but I think it was all around my self-worth and so I think that&rsquo;s why it happened to me and I think it was a catalyst for me to then look at my life and to change things that I didn&rsquo;t like and to look at what was going on and how I was sitting in this world and what I wanted out of life and HIV was a thing that made me put all of that into perspective and to then go on and do the things that I wanted to do and engage in the community which I never had before and to work on myself, like, therapy and speak with people and volunteer and mentor others and, like, leave a bit more of an impact on the world, and do something with it. So, for a lot of people, going through a HIV-diagnos can be a really challenging time and not everyone deals with it as I dealt with and part of that is down to my family and support network, but it&rsquo;s kind of what you do out of it, it&rsquo;s what you turn something into, it&rsquo;s... If something challenging happens to you in life what are you going to do about it? Are you going to pull yourself up from that? And I think that is one of the biggest things that HIV has given me and I wouldn&rsquo;t change it, because I&rsquo;m a better person today. Done.
</p>
`;

module.exports = joshua;
