const josh = `<p>
My name&rsquo;s Josh Compton. I&rsquo;m 26-years old. I come from Andover in Hampshire, but I currently live in Stockholm in Sweden. I am a Master&rsquo;s student and a teacher at the minute, in, in a middle school.
</p>
<p>
Home is a very multi-facetical concept. So, I mean this is my home where we are right now. This is where I grew up. This is the one place that has been in my life, for my whole life. So I have a strong attachment to this house, to this village, to this town. But home goes&hellip; It goes beyond just that. So&hellip; Obviously there&rsquo;s the expression &lsquo;home is where the heart is&rsquo;&hellip; At the moment I&rsquo;m, as I said, I&rsquo;m living in Stockholm. Is Stockholm my home? Is Andover my home? Is Leeds &ndash; where I studied at uni &ndash; my home? So I think home is, is the place, you know as we become adults it&rsquo;s the place we decide to make our home. And we do that by establishing connections and putting roots down and making a life somewhere. So I think for me that&rsquo;s&hellip; That&rsquo;s what home is and&hellip; Yeah. A home wouldn&rsquo;t be a home without family. So curious.
</p>
<p>
When I think of home in like a general concept then it will be here, where we are right now. And this place is a&hellip; Is a village in the countryside in southern England. It&rsquo;s, for me home is... lush rolling hills dotted with beech and oak forest. It&rsquo;s warm summer days and lots and lots of time outside. And cats have always been part of my home. I mean, obviously when I&rsquo;ve not been living with my Mum or I&rsquo;ve been, if I&rsquo;ve been elsewhere then I&rsquo;ve not had pets but we&rsquo;ve always had pets here. But... I need to highlight as well because, because I live in Stockholm so there&rsquo;s, so I have this dual-perception of what home is. And so this is&hellip; This is like what I could call my real home. And in Stockholm is kind of like my now home. And if I think about&hellip; Like, for example, if I&rsquo;m talking with any friends here in England then I say: &ldquo;Oh, I&rsquo;m gonna, I&rsquo;m going back to Stockholm on Sunday, I&rsquo;m going home Sunday.&rdquo; Then for me that&rsquo;s a whole different concept of what home is. But I guess more generally speaking I would say, like: &ldquo;I&rsquo;m going back to Stockholm.&rdquo; I wouldn&rsquo;t say I&rsquo;m going home because I am home here.
</p>
<p>
Many things did change, but what I classified as home never changed.
</p>
<p>
I mean it&rsquo;s a physical change. Regardless of whether or not you perceive it. You know, I do have a virus in my body whether it&rsquo;s controlled, it&rsquo;s still there. So, there is a physical change. There&rsquo;s also the&hellip; There&rsquo;s the perception change as well that somebody who is diagnosed then lives because, well&hellip; I shouldn&rsquo;t generalise. This is my experience. I&rsquo;ve found that for years and years I was trying to avoid getting HIV and I was always thinking about what I can do to minimise my risk and then you get it, or then I got it and I was kinda like: &lsquo;oh, well now what?&rsquo; So, I think also my diagnosis, personally, came at a time when I had a lot of other things going on in the background that were really significant. And, yeah, it was a lot to deal with because I felt that I had enough to deal with as it was.
</p>
<p>
But, as we were saying previously about trying&hellip; This isn&rsquo;t what you think when you&rsquo;re diagnosed but this is what you learn as you live a positive, a positive life. You do find that there are still obstacles in the path. And it&rsquo;s those little things that change. So&hellip; Like, I had, I was offered this job to go and teach in China and it was my dream. I&rsquo;d been working towards it, studying Chinese for three years. I was quite good, well, I still I am I guess. Just a bit rusty. But, yeah. I couldn&rsquo;t go in the end. So that&rsquo;s just one way about&hellip; That&rsquo;s just one example of how many different ways in which a life can change. But my concept of home is still the same.
</p>
<p>
I think here in the UK&hellip; I mean, I was actually diagnosed in Brasil believe it or not, and I was on holiday in Brasil whilst I was studying and living in Chile, so in a roundabout way I managed to, like, start treatment here although I was diagnosed over there. And here, much the same as in Chile and in Brasil as well, like I didn&rsquo;t find any exclusion. I didn&rsquo;t see&hellip; I mean, it&rsquo;s not something that I go around proclaiming to people and it&rsquo;s not something that I did go around proclaiming to people. So I kind of, in a way, I was never excluded from spaces but I felt that in certain spaces I&rsquo;d have to be a bit cautious about what I said. And with this example that I said about China I mean, yeah. I had a job there. I was paying for my visa and it all fell through. So, in that instance that was a big exclusion.
</p>
<p>
I just, I feel like there&rsquo;s so much stigma surrounding HIV and there&rsquo;s so much expectation. Well, this is my perception. I feel that there is a lot of weight on young gay men&rsquo;s shoulders about getting HIV and as I said it was something that I really tried to avoid. And then I got and I kind of felt like another statistic, like: &lsquo;Oh another one.&rsquo; &lsquo;Cause I was under 25 at the time.
</p>
<p>
And also because, people -. The public knowledge isn&rsquo;t there. So, I guess it&rsquo;s kind of like if you&rsquo;ve got, if you&rsquo;ve got some kind of progressed form of cancer and then you go telling everybody the ins-and-outs of your treatment and what that means and, like, people&hellip; Like, you just wouldn&rsquo;t do that because number one, these people don&rsquo;t need to know all that information, number two, it&rsquo;s probably very scientific and a lot of people won&rsquo;t follow and with HIV it&rsquo;s kind of similar. You don&rsquo;t, we don&rsquo;t need to explain to other people what it is. But&hellip; Well, possibly some cancers do but cancer don&rsquo;t have the same stigmatisation as what HIV does. So, that&rsquo;s a difficult one. And there was a time, after diagnosis &ndash; maybe like a year after diagnosis &ndash; that I was like very happy to speak about it in conversation even with people I didn&rsquo;t know very well. Because I wanted to be one of those, like, stigma warriors but I got tired. It&rsquo;s something now that I currently, like, in this phase of life that I find myself I&rsquo;m not happy with the fact that I&rsquo;m HIV-positive but I can&rsquo;t change it. So, I just&hellip; Obviously I&rsquo;ll talk about it with my close friends or, you know, if I&rsquo;ve got a doctor&rsquo;s appointment &ldquo;&hellip; oh yeah guys, I&rsquo;ve got a doctor&rsquo;s appointment or whatever,&rdquo; but it&rsquo;s not something that I&rsquo;ll just chit-chat about because&hellip; Yeah. People judge.
</p>
<p>
I found, in my personal experience, that after I was diagnosed I&hellip; My life completely changed because it was something that I tried to avoid for so long and&hellip; I didn&rsquo;t get it by being a saint. I was taking a lot of risks and I was exposing myself and when I kind of woke up from the trance I was like: &ldquo;Josh, why are you behaving like this? Stop.&rdquo; It was too late.
</p>
<p>
Yeah, so basically I feel that I have, that I put the label on myself, like&hellip; You&rsquo;ve been diagnosed with HIV therefore you need behave in this way. And since my diagnosis I&rsquo;ve really struggled with lots of things. In a certain perspective you can see that that&rsquo;s me creating like a self-fulfilling prophecy. Okay, I&rsquo;m HIV-positive therefore&hellip; Which isn&rsquo;t the case. Obviously my personal situation is like an interconnected web of many different things. This is just like one of the strands.
</p>
<p>
I think also&hellip; at least in my experience, I feel like I had a very good sexual education when I was in school and I think that most &lsquo;90s kids in the UK could probably say something similar. And so, like, part of this neo-liberal political economic model that we&rsquo;ve got in place, like a major factor of that is the individualisation of responsibility which is like a political stance that the Government is taking, so the Government &ndash; and I&rsquo;m not saying that the Government should protect us from HIV or that they should do&hellip; that&rsquo;s not what I&rsquo;m saying &ndash; but what I&rsquo;m saying is, like, with making people responsible for their own actions and choices and whatever, then it puts the responsibility on the person if something goes wrong, such as a diagnosis. And so I think that with HIV because of this, like, taboo, because it&rsquo;s sexuality and because of, like this, political programme or whatever you want to call it, as well as many other factors that I&rsquo;ve probably missed&hellip; it makes it difficult for people to talk about it and for people to break down the stigma and also I think, like&hellip; The Government in the &lsquo;80s and how they dealt with the AIDS pandemic, like&hellip; I mean I didn&rsquo;t live it, I wasn&rsquo;t there. I can only go from what I&rsquo;ve heard other people say that they lived or experienced. And from what I&rsquo;ve seen.
</p>
<p>
And you know, there&rsquo;s&hellip; I don&rsquo;t know if you&rsquo;ve seen the film &lsquo;Pride&rsquo;? Yeah, so there&rsquo;s a bit where &ndash; what&rsquo;s the young kid&rsquo;s name? Is it &lsquo;Sutton&rsquo; they call him &lsquo;cause he comes from Sutton? And he lives with like just a normal middle-class family and they&rsquo;re sat around watching television and it comes up, like, AIDS, and the father&rsquo;s like &ldquo;&hellip; anally-injected death sentence.&rdquo; And it&rsquo;s like: not necessarily. So there&rsquo;s a whole image that&rsquo;s&hellip; that was created due to the political model of the time which was Conservative, right-wing, neo-liberal, traditional, like&hellip; black and white, male or female, like&hellip; And society has progressed but the way of dealing with this virus is, I feel it&hellip; In certain respects of course it&rsquo;s progressed a lot but in the way that it&rsquo;s viewed I still think it&rsquo;s... I mean, it&rsquo;s always going to be tainted by that image because that&rsquo;s how it came about.
</p>
<p>
Yeah also if&hellip; At the end of the day the original image and message that was put out there was by the Government and the media, like probably from order of the Government. Are the same powers going to do something about it now? No. Any change is going to come from the bottom up. So, this is where on a societal level I feel it&rsquo;s different to an interpersonal level because I can be talking to my mates and you know with some of my closest friends we make jokes about the fact that I&rsquo;ve got this and it&rsquo;s not an issue. But then with some of my other friends like I wouldn&rsquo;t even dream of mentioning it. So, everything&rsquo;s contextual, everything it varies. But in order to have, like, the public knowledge that I feel is lacking about the virus. The only place it can come from is up, so&hellip;
</p>
<p>
Yeah, I&rsquo;ve been reading a lot into &ndash; well, a lot &ndash; I&rsquo;ve been reading a bit into philosophy like the past couple of years and it&rsquo;s interesting seeing that if you look at society as being a base &ndash; which is us &ndash; and then a pillar which connects us to the, like, overarching superstructure &ndash; which is, like, pretty much anyone with power, so like the State, pharmaceuticals, oil, landowners, techies, in like a contemporary context, and everything that we&rsquo;re&hellip; Everything that we live and everything that we do and everything that we see is a created reality according to the benefits of... or according to the viewpoint of those who benefit most from the system. So, I think that, like, the reason why this controversy came about is because in the &lsquo;80s obviously people were struggling for queer rights and things like that. It was very easy to scapegoat that group of people. And today we have a whole host of rights that we never could have imagined having back then and society has progressed and I can walk down the street holding hands with a guy and probably not get any harassment. But this&hellip; We&rsquo;re still part of this structure, so&hellip;
</p>
<p>
And there are so many different parallels that you can draw and I think, like with corona, I think, like there are so many things that if you like read between the lines or if you look at the fine print or if you don&rsquo;t just listen to the mainstream media, if you like look around and question then &ndash; at least this is my opinion; I&rsquo;m sure there are many people that would say something else &ndash; there are&hellip; Something&rsquo;s not quite right. I feel like an image is being created for a certain end and something very similar happened with HIV.
</p>
<p>
Yeah it&hellip; It&rsquo;s like me coming back to the UK from Sweden where we&rsquo;ve had pretty much all the freedoms that we need, come back to the UK and I&rsquo;m having a discussion with my Mum and she says, Josh, like: &ldquo;You can&rsquo;t go out. If you go out and the police find you they&rsquo;ll fine you.&rdquo; And I&rsquo;m like: this is a dictatorship.
</p>
<p>
Okay. So I mentioned I was diagnosed when I was living in South America and then that was in my sandwich year whilst I was at uni and I was at uni in Leeds. So when I finished up in South America I spent the summer here in Hampshire and then I went back off up to Leeds and I went to the virologists &ndash; is that what you call them in English? It&rsquo;s, er&hellip; There are a lot of words that I learnt first in Spanish and I&rsquo;m, like, vir&oacute;logo? Virologist? So I had an appointment with my virologist in Leeds and I just like broke down into tears. And they&rsquo;d said to me a couple of times before, like, let&rsquo;s hook you up with Leeds Skyline and Leeds Skyline is an NGO that works with the HIV-positive community in Leeds or in West Yorkshire and&hellip; I always said like no no no no no, I don&rsquo;t need that, like I can manage this. I also had a certain image about what that place could be like and the kind of people that might go there and at the time I was like, how old was I? I was 22, you know I was a uni student, I didn&rsquo;t&hellip; The image that I had didn&rsquo;t represent how I saw myself. When I broke in, burst down into tears, as I just said, the nurse was like: &ldquo;Okay, Josh. I&rsquo;m going to call them and you can speak to them and if you decide that you don&rsquo;t want to go then that&rsquo;s fine, but I really want you to speak to them.&rdquo; And I spoke to them and they came to the hospital and they picked me up and we walked a few blocks and we walked to their office and they told me about this, like, group therapy session that they have called PACT, which is Positive and Coping Together, which is a GBT men&rsquo;s group for HIV-positive men. And I speculatively went to one session and I felt incredibly uncomfortable because I was the youngest person by about 25 years. They had a certain queer charisma that&rsquo;s characteristic of gay men of that age, that I didn&rsquo;t identify with and I felt uncomfortable, but I went for a couple of weeks.
</p>
<p>
My Mum taught me when I was kid like that first impressions are super important but if it&rsquo;s something new then try it for a good few weeks and then decide. So I went, for a good few weeks and I&hellip; It used to be the highlight of my week. Eventually. Because I found a space in which I could like really speak freely, about what I was living and what I had lived previously to that. And&hellip; Not only did we have this space where we offered, like, I don&rsquo;t know, like sessions to deal with, how to deal with their mood, and sessions that dealt with prioritisation skills and whatever, like workshops, but we also had, like, heart-to-heart sessions where the co-ordinator would go around and say: &ldquo;Okay, like, person 1: how was your week? Person 2: how was your week?&rdquo; And, that year of my life was very very fucking difficult. And so it created a space for me to be able to voice these things that I was going through because I couldn&rsquo;t speak to my family about them, because I suffered some horrible discrimination from my family when I came out with HIV.
</p>
<p>
Skyline is like the most positive thing that came out of my diagnosis and it&rsquo;s something that I&rsquo;ve constantly looked to replace when I&rsquo;ve been somewhere else. And when I moved to Spain the first place I went to was &ndash; what&rsquo;s it called? The Comit&eacute; Anti-SIDA &ndash; and I was like: &ldquo;Okay guys, like, I come from Leeds and they have this organisation and I had a psychologist before and I used to get massage sessions and group sessions and what can you guys give me?&rdquo; and they&rsquo;re like, they went: &ldquo;We don&rsquo;t work like that.&rdquo; They basically&hellip; Obviously they have a certain degree of like pastoral care and support services that they can offer. They&rsquo;re more of like an info provider and they&rsquo;re more &ndash; I feel, at least &ndash; they&rsquo;re more political activists than what they are, like, a care-giver. I feel like the care-giving goes on the side.
</p>
<p>
And then when I moved to Stockholm as well I was like: &lsquo;Okay, like, what organisations can I find that can support me?&rsquo; Because I found that it wasn&rsquo;t just PACT at Skyline, but it was the other services that they offer that allowed me to interpret what I was living and what I had lived because I was sexually abused as a child and&hellip; That basically fucked everything and&hellip; It wasn&rsquo;t until I started going to Skyline that I accessed that period of my life as abuse. It was a period of my life that at the time I just ignored and like never wanted to speak about it again and then it &ndash; after having gone to a few sessions in Skyline I was like, the penny dropped and boom, like, okay this is an issue that I need to deal with. It&rsquo;s an issue that I haven&rsquo;t been dealing with properly and it&rsquo;s an issue that has caused me other recurring issues but, yeah, these&hellip; Rome wasn&rsquo;t built in a day. And these issues can&rsquo;t just be unpicked in a matter of months, it&rsquo;s going to take years of work, so&hellip;
</p>
<p>
I see a psychologist in Stockholm who I&rsquo;ve been seeing since July and I am going to be, or I started in December, to see a nurse and a doctor once-a-week as well and we&rsquo;re going to drum up some kind of plan or whatever that will deal with, like, the psychological trauma, the drug issues and then everything else that comes because I have psychological trauma and drug issues. But yeah&hellip; Yeah, as I said it&rsquo;s all like an interconnected web of things
</p>
<p>
Yes, I found places. But no, I haven&rsquo;t found the support just yet. And that&rsquo;s part-and-parcel because of many different things. Corona, being one thing. Another thing being my timetable&rsquo;s not been matching up with the appointments being offered me. There&rsquo;s one organisation called NOAXIKE and they &ndash; I don&rsquo;t know if it was an email or I just saw it online - but they have like a young person&rsquo;s service or whatever, but in order to be, like, welcomed in, you need to have like a &ndash; what do you call it? - like an orientation. Which in corona times you can&rsquo;t have. And so they tried to have like a digital one instead. But obviously I&rsquo;m working full-time, I&rsquo;m studying part-time too, I&rsquo;m trying to find time to have a social life. So, I have found the organisations and actually in December we left on a note to say &lsquo;okay, let&rsquo;s get in touch in Jan&rsquo;, so the ball is rolling.
</p>
<p>
There&rsquo;s another one&hellip; Oh yeah, it&rsquo;s called &lsquo;PositHIVa Gruppen&rsquo;, like positiva which is Swedish for positive and HIV in the middle, PositHIVa Gruppen, and they have a group called Young &amp; HIV and this group they, like I&rsquo;ve been to a couple of their events actually. We had an art therapy session in October or November, which was rather delightful and we were supposed to go in December to like a house in the Stockholm archipelago and stay for the weekend but it got cancelled. Corona-cancelled. So, like there are a couple of things that are kind of in the pipeline that haven&rsquo;t really surmounted to anything just yet but I&rsquo;m in like the whats-app chat group for this Young &amp; HIV group. I don&rsquo;t know any of the people there yet because we&rsquo;ve not met, but these are things that I know will unfold and will, like, blossom into something this year. But I think as a young person and as a person who comes from a background where there&rsquo;s been trauma, especially in the childhood, I think it&rsquo;s imperative for me to find that support because, yeah&hellip; I just can&rsquo;t manage. So&hellip; And also, like, I can&rsquo;t expect, well&hellip; I do expect but perhaps I shouldn&rsquo;t expect my family to offer that because you know they&rsquo;re not trained in this stuff, at the end of the day. So&hellip; Hm.
</p>
<p>
Yeah&hellip; Any affect that HIV had on my closest relationships I&rsquo;m going to say was temporary. I&rsquo;m not sure if those relations would say the same but that&rsquo;s how I see it. And initially, when I came out to my family and I told them that I&rsquo;m HIV-positive &ndash; and I&rsquo;m happy for this to be published or whatever &ndash; yeah I was met with discriminative comments and a lack of understanding and absence of care that I needed. But then, you know, over the following months, I could see that they tried to make things right but I wasn&rsquo;t so perceptive to them trying to make things right because I was too hurt. And in my own way I still am. But that&rsquo;s only family.
</p>
<p>
All of my friends, like, they only expressed concern. Like: &ldquo;&hellip; we&rsquo;re concerned, we&rsquo;re concerned that your future might not be so healthy.&rdquo; Whereas my family was more the image that being HIV-positive carries with it. So, I would say that all of my&hellip; None of my friendships were affected by it and if anything it kind of drew me closer to my friends. It allowed, it encouraged me to be more open with them and also, like, for example my final year when I was in Leeds I was living very very promiscuously as like a coping mechanism and, you know, there&rsquo;d be guys coming in and out all over the place, whatever, and they would never express like discontent with that or like disgust with that or anything. All they&rsquo;d say is like: &ldquo;If you&rsquo;re behaving like this because you want to, fine. If you&rsquo;re behaving like this and it&rsquo;s covering, like, something else up then we want to help you to fix that.&rdquo; So I would say, if anything, it kind of strengthened my friendships. But, yeah, it did definitely temporarily have a negative impact on my family relations.
</p>
<p>
This past year in Stockholm I have been in a very bad place. I was kind of love with this guy who I met studying in Chile who lived in New York and I went to New York to see him in March. And I was in a really bad place mentally at the time. I wasn&rsquo;t happy living in Sweden, I had no money, I wasn&rsquo;t happy with my career prospects, with my future outlook in general. I was taking a lot of drugs. My mental equilibrium was just like not there. And when I went to visit this guy who I was, like, kind of in love with, he just wanted one thing and I wasn&rsquo;t in the position to give him that thing at that moment and I tried to explain that very expressly and because of the way that things turned out regarding consent between the two of us, I came back to Sweden or I went back to Sweden heartbroken and in a worse position than I was in. And then I lost my job in May and I had to find another one which I did get so that&rsquo;s fine, but&hellip; All of these things really knocked me sideways and so I wouldn&rsquo;t say that my space that I have in Stockholm is my safe space.
</p>
<p>
And because of the turbulence in the relationship with my Mum, I also wouldn&rsquo;t necessarily say that this is my safe space either. So, I guess, like, my safety that I construct for myself is routine and it&rsquo;s more of a &ndash; what&rsquo;s the word I&rsquo;m looking for &ndash; it&rsquo;s more of a conceptualised vision of space rather than a physical vision. And so I&rsquo;m feeling safe if I&rsquo;m exercising like five days a week. I&rsquo;m feeling safe if I&rsquo;m sleeping properly. I&rsquo;m feeling safe if I&rsquo;m eating properly. I&rsquo;m feeling safe if I&rsquo;m not going out and getting shit-faced and going to orgies and having unprotected sex with people I don&rsquo;t know and whatever. And as soon as one of those things gets knocked off then the safe space, be it not physical but conceptual, disappears. So, yeah. I think&hellip; I mean, I&rsquo;m moving house next week when I go back to Stockholm and with all these things that I have in place with the doctors and the nurses and like I reached out to work for support as well and they offered me support and with everything, then I&rsquo;m hoping that I can&hellip; My new physical space can be my new safe space. We&rsquo;ll see what happens.
</p>
<p>
I think it will because I&rsquo;ve got no more patience to deal with it, not being that way. So, I think it&rsquo;s time for that lasting change.
</p>
<p>
I would say I&rsquo;m very&hellip; I&rsquo;m very outgoing, I&rsquo;m very chatty. I&rsquo;m very friendly. I wear my heart on my sleeve so I&rsquo;m very emotional. I&rsquo;m very sensitive, very fucking sensitive. I&rsquo;m&hellip; I have so much love to give and that is shown in how I relate with my friends, in how I might touch my friends like, instead of, like keeping a&hellip; Especially living in Sweden which is a society very much of personal space like I&rsquo;m always, I&rsquo;ll put my hand on my friend&rsquo;s shoulder or I&rsquo;ll like play with their hair. I&rsquo;ll use little words of affection, I&rsquo;m a very affectionate person.
</p>
<p>
But also&hellip; I feel like I have a lot of contradictions in my life and those contradictions sometimes lead people to have an image of me that isn&rsquo;t accurate or isn&rsquo;t wholly accurate and sometimes because of the coping mechanisms that I have generated for myself to deal with my childhood traumas and then my diagnoses and all these other things that have happened in my life&hellip; I feel that simultaneously it creates, it creates a different, a different like version of me, kind of. You know, if I&rsquo;m, if I&rsquo;m in a bad place and I&rsquo;m making poor decisions and I&rsquo;m going out and buying drugs and then like staying out all weekend or like not eating properly or whatever then the people that I meet in that window of time will have that image of me. But actually, like, you know I&rsquo;m Mr Compton, I&rsquo;m a teacher, I have a position of respect in the community and I go to school and I banter with the kids and&hellip; I received a gift actually for Christmas from school and it&rsquo;s a little, hand-drawn, like, framed piece of paper and some of it&hellip; A kid has just drawn a stick-person and it says &lsquo;Mr Compton you are strict but you are right.&rsquo; So, on the one hand there&rsquo;s Josh who, like, goes out and parties and&hellip; I don&rsquo;t need to go into all the ins-and-outs but&hellip; And then on the other hand there&rsquo;s teacher Josh and there&rsquo;s student Josh and there&rsquo;s family-guy Josh.
</p>
<p>
It&rsquo;s not just, yeah. It&rsquo;s not just one label, one box, one category. It&rsquo;s, you know, we are diverse and dynamic beings, we&rsquo;re constantly changing. Oh yeah, like how I would describe myself. But yeah like&hellip; I&rsquo;m very outdoorsy. I like to go hiking, I like to go camping, kayaking, cycling. I&rsquo;ve even started running outside thanks to corona, &lsquo;cause I can&rsquo;t go to the gym. Even if it&rsquo;s minus-2 degrees. Yeah, like&hellip; There are so many things&hellip; I love to bake. I&rsquo;m always baking. I made a banana bread just a few days ago. I baked mince pies in Sweden. I have friends over and I, like, it might be like six or seven friends and I&rsquo;ll make a massive Thai curry. Or I&rsquo;ll do like a huge Shepherd&rsquo;s Pie or something and we&rsquo;ll have drinks and we&rsquo;ll play cards. I&rsquo;m very, I&rsquo;m very social. I live off being with other people and keeping busy and doing things and getting out there and&hellip; I have a thirst for knowledge. That&rsquo;s why I love to travel. That&rsquo;s why I love languages as well. I speak twelve languages.
</p>
<p>
So, to like some degree of fluency, bi-lingual English and Spanish. Totally. And then to varying degrees of fluency we have French, Italian, Portuguese and Swedish. And then I can speak, like, kind of good but now very rusty Mandarin. Bist keine Deutsch sprecken. Because I live in Sweden. And all the Swedish has pushed the German out of my memory. Because they&rsquo;re so similar. I mean, Swedish is very similar to English anyway. But I had a couple of German classes at school that I was covering and I was talking to the kids and I was trying to speak German and I just spoke to them in Swedish and they were like: &ldquo;You do realise you&rsquo;re speaking to us in Swedish?&rdquo; And I&rsquo;m like: &ldquo;Ah!&rdquo; And then I can speak, like, kind of like basic conversational Polish. Like introductory Arabic, Hebrew and Mapudungun which is the language of the Mapuche people from Chile, which I studied when I was out there studying. So, yeah&hellip; I like my languages. I really want to work on my Arabic. I need to get my Chinese back up. And I&rsquo;d like to learn&hellip; I always said Hindi, but maybe Sanskrit would be a bit more useful because if I learned Sanskrit then it would be easier to understand the other Indian languages I think.
</p>
<p>
I was at the Bishopsgate Institute and then obviously when I left London that was that. I mean, Stockholm has a massive Arabic-speaking population and it&rsquo;s very easy to learn in Stockholm, but I don&rsquo;t have the time at the minute, so, you know, I&rsquo;m taking some time last year and this year to focus on me and my things and my progression and my, like, personal development and until that&rsquo;s done I&rsquo;m probably not gonna&hellip; I mean, obviously Swedish will come because I&rsquo;m living there but I shan&rsquo;t be embarking on any new learning adventures. I don&rsquo;t think.
</p>
<p>
I&hellip; London&rsquo;s so cosmopolitan, obviously, and I never met anyone from Mongolia until I went to Stockholm. And there are a lot of Mongolians in Stockholm. And I was in a pub with a friend of mine and there were these, like, kind of central, East Asian-looking people that were speaking a very funky language and I was like: &lsquo;What the fuck are they speaking?&rsquo; And I listened and I listened and I listened and I&hellip; So many new sounds that I hadn&rsquo;t heard before and I&rsquo;m like: &lsquo;What language is this?&rsquo; And I asked them where they were from and I thought they were going to say something like Tajikistan or Kyrgyzstan and they said they were Mongolian and I was like: &lsquo;Ohhhhh.&rsquo; And ever since I spoke to those people and I asked them where they were from and, like, like I can figure out&hellip; And it was two women and they said: &ldquo;As long as you don&rsquo;t think we&rsquo;re Chinese then that&rsquo;s fine.&rdquo; I said: &ldquo;No, you don&rsquo;t look Chinese.&rdquo;
</p>
<p>
Be it necessary or not, HIV incredibly negatively impacted my life. It turned everything on its head. My relationship with my family changed, albeit temporarily, but the.. on my side of the, of the coin I guess, the temporary changes that then kind of sorted themselves out for me had more longer-term impacts. And yeah. Ever since that happened, my relationship with some members of my family is different. It.. That doesn&rsquo;t mean to say that it can&rsquo;t change again in a positive light and that is what I&rsquo;m looking, at what I&rsquo;m working on now. But I think&hellip; If all of a sudden you&rsquo;re diagnosed with asthma, you&rsquo;re not going to turn around and say: &ldquo;Oh, fuck. My life is ruined!&rdquo; You&rsquo;re not going to think: &lsquo;Oh, like I can&rsquo;t talk about this in public or I can&rsquo;t, I can&rsquo;t, like&hellip;&rsquo;
</p>
<p>
Yeah, or be an activist for Asthma UK or whatever the charity&rsquo;s called. But, you know, as soon as you decide to affiliate yourself with&hellip; What&rsquo;s the one that we have in the UK? The&hellip; AIDS, HIV/AIDS charity? The national one? Terrence Higgins Trust, that&rsquo;s the one. Oh my god, I&rsquo;m becoming a foreigner in my own country. The&hellip; yeah, like as soon as you affiliate with that and you say and, I don&rsquo;t know, you&rsquo;re at work and your colleagues invite you to the pub and you say: &ldquo;Oh no, I can&rsquo;t. I&rsquo;ve got a meeting with the Terrence Higgins Trust.&rdquo; Like, it&rsquo;s, that is like telling them that you&rsquo;re positive and it&rsquo;s an invitation for them to create a judgement about you. But the reality of HIV, if it is well-managed and if you&rsquo;re medicated as you should be, and if you&rsquo;re undetectable then HIV is much easier to live with than asthma. I know because I have both. Or diabetes. And, you know, there are people who will happily say like: &ldquo;Oh, I can&rsquo;t have those biscuits I&rsquo;m diabetic.&rdquo; But there&rsquo;s no way in hell I&rsquo;m going to turn around and say: &ldquo;Oh no, I can&rsquo;t do this because I&rsquo;m HIV-positive.&rdquo; Because number one, there&rsquo;s no need for that anyway because it doesn&rsquo;t change anything but number two, because you don&rsquo;t want to invite those people to make those judgements. And so, yeah&hellip; What you said earlier about inclusion and exclusion &ndash; and like the discourse about creating space - I&rsquo;m a human geographer, so I think a lot about sociological issues and space all the time - and when I was, in a way &ndash; temporarily or not &ndash; rejected by some members of my family I had to find another way to create a space that was safe for me in order to be able to progress and process everything. And&hellip;
</p>
<p>
Yeah. I mean, in hindsight, potentially I could say it&rsquo;s the best thing that ever happened to me because it allowed me to see my life through a different lens and highlight long-standing issues in my life like my child abuse which I didn&rsquo;t access as child abuse until I was positive and I began to question: Why am I positive? Why did I take those risks? Why did I put myself in those situations? Well, let&rsquo;s trace it back.
</p>
<p>
So, I mean it created a very very negative outlook for me and especially when I lost my job in China, which I had been studying specifically for, for three years and I was&hellip; You know, I fucking studied Chinese in Chile from Spanish in order to, like, facilitate this. You know, I was really destined, like, not destined, but like I was really driven to go and do it and then I couldn&rsquo;t because of HIV and that leads you to have a very poor image of yourself because there&rsquo;s also the voice in my head that&rsquo;s like: &lsquo;Oh, you could have used condoms.&rsquo; This was my case, obviously there&hellip; Not everyone who gets HIV gets it because of sexual decisions they take. But in my case that was the case. And, it&rsquo;s so unnecessary to have any of this discontent and any of this heartache with an HIV diagnosis. So&hellip; but you know, this is what, this is what we have to deal with. And this is why I want to participate in this project, because it&rsquo;s &ndash; as I said &ndash; true, like, lasting change has to come from above but that is absent. So, the resort that we have is grass-roots, bottom-up, doing things like this. So&hellip; There are so many different things that happen all around the - . I went to New York, as I said in March, and I walked past the AIDS Memorial. You know, that&rsquo;s another way. There&rsquo;s so many different ways of, of creating a new reality for HIV-positive people. There&rsquo;s no reason why it has to be a negative reality.
</p>
<p>
Maybe not necessarily the stigma but breaking down the, like, social myths. Yeah. And, like, I&rsquo;ve done many things in my life that I&rsquo;m not proud of and I don&rsquo;t, maybe there are some people who could consider that when I talk about having been sexually abused as a child I use it as like, as like a get-out-of-jail-free card, like, oh, well, you know, I lived through this so therefore, you know, it&rsquo;s okay. And it&rsquo;s not. But it helps people to understand and it&rsquo;s through understanding that we can, we can create better futures and brighter futures because, I mean, if I didn&rsquo;t get the grades I got, thanks to my Mum who really encouraged me academically at school, I don&rsquo;t know what the fuck I&rsquo;d do stuck here in Andover. Working in a factory or a warehouse and having to just get on with a mundane life.
</p>
<p>
So, it&rsquo;s important that we take these things into consideration and obviously as a teacher, I got into education because I really enjoyed school. At the beginning. But I&rsquo;m still in education because when kids are swearing at me or when kids are being little shits and cellotaping their eyes closed and trying to cut it off with scissors or any sort of attention-seeking behaviour it&rsquo;s because there&rsquo;s a problem. And, I&rsquo;m just a substitute teacher, like, I&rsquo;m not even like a contractual worker. I don&rsquo;t have a salary. I&rsquo;m just paid by the hour but when I go to school in Sweden and I see that this kid who&rsquo;s usually problematic is being, like, extra, or he&rsquo;s starting fights or he&rsquo;s&hellip; I should probably say &lsquo;they&rsquo;, or they are like just being more, more difficult to deal with than normal, it&rsquo;s because something else is going on and because I&rsquo;ve lived through it and I&hellip; The arguments I used to have with my Mum when I was a teenager... and that came from the imbalance of power in the parent/son relationship because I was having a different relationship with a man and there are so many different scenarios that can cause kids to behave erratically and it&rsquo;s, yeah&hellip; And people who come from backgrounds like mine need to be in education because they can see.
</p>
`;

module.exports = josh;
