const philip = `
<p>
 My name is Philip Baldwin. I am a human-rights activist and writer with a particular focus on HIV, LGBTQ+ issues, homelessness, asylum and faith inclusion.</p>
<p>
 I was diagnosed with HIV in January 2010 when I was 24 years old. The HIV diagnosis took place over my lunch break from work. When the nurse told me that I was HIV-positive it came as a complete shock. It took me about three years to come to terms with my HIV. It was not until the end of 2012 that I had the confidence to tell my employer or my parents that I was living with HIV. Sometimes it can be hardest to tell the people you love the most. From about 2014, I began to get involved in HIV campaigning as I wanted to help and advocate for other people living with HIV. I was fortunate in that I was offered a column by the Huff Post discussing what it is like to be gay, HIV-positive and working in financial services as a lawyer, which was my job at the time. My activism snowballed from that point. I now write for many different publications and am also a trustee of a number of charities. I know that I am very fortunate to have the voice that I do on HIV and LGBTQ issues. My HIV was at first incredibly frightening but I now feel more empowered than ever before. </p>
<p>
 Home for me is my apartment in London. I&rsquo;ve lived in London since my early twenties and have always felt at home in the city. Coronavirus aside, it always feels alive. It has a special energy. It&rsquo;s a joy being close to museums, theatres and other cultural institutions. There are many other parts of the UK which have special memories, such as where I grew up in Cumbria, Edinburgh &ndash; where I went to school &ndash; or the universities where I studied. London is home, though, and I would say that my apartment is my sanctuary.</p>
<p>
 My apartment is contemporary in design and I&rsquo;m surrounded by books relating to my degrees and LGBTQ campaigning. I&rsquo;ve lots of photos of my friends. I live alone and don&rsquo;t really cook so in terms of smells I&rsquo;m afraid it doesn&rsquo;t get more exciting than the occasional scented candle. I live near the river Thames and you can often hear the boats making their way up and down the river. Importantly, my home is somewhere for me where I feel safe. As a writer, I do often spend days at my desk in my apartment and it is a place of nourishment, comfort and inspiration. </p>
<p>
 I wasn&rsquo;t actually living in my current apartment when I was diagnosed with HIV, back in 2010. I moved several years ago. I don&rsquo;t believe my perception of home changed as a consequence of my HIV-diagnosis. It is worth noting that following my diagnosis I left the sexual health clinic and made the short journey back to where I was living. I curled up on the sofa in a foetal position and cried. I went back to my apartment because, again, that was where I felt safe. At this time of crisis, my apartment is where I sought shelter.</p>
<p>
 In terms of positive reactions, I&rsquo;ve had people I&rsquo;ve never met before come up to me, tell me I&rsquo;ve read my columns or an interview and they confide in me that they&rsquo;re HIV-positive and haven&rsquo;t told anyone else. I always emphasise that they should reach out to peer-support services but it&rsquo;s touching to know that I can have impacted even a few people in a small way. In terms of the strongest negative reaction, I went on a date with a guy a few years ago. We were sitting at the bar and had just ordered some drinks. I hadn&rsquo;t&hellip; I mentioned that I had been writing something about HIV the other day and he asked me if I was HIV-positive and then flipped out. It was really strange, He called me dirty and a slut in the bar, loudly in front of lots of other people. He left shortly afterwards but that really shocked me. It demonstrates how real stigma of HIV remains.</p>
<p>
 For the first few years, following my HIV-diagnosis, I didn&rsquo;t tell my employer about my HIV-status. I had previously felt comfortable in my work environment but now I suddenly had this secret. I felt I had to be furtive about my HIV at work and that changed the dynamic in the workplace a bit, although I never felt excluded. In terms of my living situation my HIV status has never impacted this.</p>
<p>
 My HIV-diagnosis has actually brought me closer to my parents. I&rsquo;m lucky to have their support. However, my friends were the first people I spoke to following the HIV-diagnosis. I needed their support. They were very kind, one of them even accompanying me to my first appointment at the specialist HIV clinic. </p>
<p>
 I have another safe space now. I am gay and Christian. Around 2013, I began to explore faith and I was fortunate to find inclusive churches in London. I am very aware that many LGBTQ+ people have not had this journey, some being rejected by their faith communities and families on account of their sexuality or gender identity. The church I attend most often was built at the end of the seventeenth-century but has a modern interior. It&rsquo;s quiet, contemplative. I was confirmed in 2015. The churches I attend are Church of England churches and I get a lot of support from my priests and the congregation. Church for me is a place of peace, prayer and community, but also where I gain strength to push forwards with my campaigning. I see a happy and confident young man who is trying to do his very best.</p>
<p>
 I&rsquo;d just like to thank you for inviting me to participate in this project. If anyone would like to find out more about my campaigning, I can be found on Twitter and Insta @philipcbaldwin.</p>
`;

module.exports = philip;
