const stephen = `
<p>
Participant Transcript: Stephen
</p>
<p>
My name is Stephen Hart, I am an actor and a YouTuber and I have been HIV-positive since 2006.
</p>
<p>
When I think of home I think of, I think of home, I think of my home, the place that I feel secure in, the place that I feel comfortable in, the place that has things around me, you know, that reminds me of people, photographs or ornaments or my posters in my hallway, you know, that remind me of what I've done with my career and things like that, so this... This home is home for me. It's kind of... Yeah, it all falls under that umbrella of a place that makes me feel safe.
</p>
<p>
My home is... It's a bit like an art gallery, a museum. That's the best way to describe it. I have pictures. I have all my pictures in my hallway of all the different shows that I've seen or I have been in and that I've worked on or that have friends in. And then I have a massive DVD collection which is something that people don't have anymore, but each one of these films has a meaning for me and a connection with a time and a place in my life and then photographs. I'm a big photograph buff as well, so I have photographs of people and places and I like looking at them every now and again, it's good memories. Photographs, you know, because of the memories that they can stir up, the good and sad memories you know. I think photographs do that, don't they? They're very, you know, they can make you feel, they can take you back to a time and a place and... Yeah, so photographs for me are very, very important. That would be the object that I think I would connect the most with.
</p>
<p>
I suppose my feeling of home after my diagnosis it became... It's always been important, it's always been very important. I was homeless when I was younger, so home has always been very important. After my diagnosis, I think it became even more important because I had... Once I closed that door, it gave me a place to fall apart, because for the first two years after my diagnosis I needed to fall apart and I needed a safe space to do that because I couldn't do that... I was still working, during the day I was still acting very normally, you know, and I wasn't allowing people to see what was going on inside so... I would close the door so my home became that safe space to fall apart in. But as the years have gone on it's also become a place where I've grown so I don't fall apart very often now. It's more a place of comfort.
</p>
<p>
I became homeless when I was fifteen-and-a-half. My mother... I was adopted and my adopted mother had schizophrenia and from the age, from when I was about thirteen to when I was fifteen-and-a-half her health was getting progressively worse and it was something that was a secret. It was another secret that I wasn't allowed to tell anybody about and that she didn't disclose to anybody, so it meant that behind closed doors our world was falling apart but nobody knew and eventually, by the time I was fifteen-and-a-half, I was starting to have my own opinions and my own beliefs , my own thoughts and things ,and that with her schizophrenia just.... It enraged her, it made her angry and after a huge argument one day she kicked me out. She told me I was adopted, which I didn't know. So it was kind of a double-whammy and I became homeless and I spent six months living on the streets in Glasgow. And it was really, really tough because I was so young, I was so alone because I couldn't tell anybody so I continued to go to school for six months. Every morning I would, sorry, get up in the morning from where I was sleeping. I would go to the bathrooms in school, I would get washed, I would get changed, I would be in school for 7 o'clock and I did that for six months and didn't tell anybody because, because that's the only thing I'd known throughout my life because I'd always been told ‘don't tell anyone', so I didn't tell anyone for six months and it wasn't until the end of six months that one of my teachers clicked and started to put two-and-two together and spoke to people at school and then they contacted social services and social services came and spoke to me and it all came out after six months, but living on the streets at any age is tough but being a child living on the street is really hard. So it was a tough, tough time, you know, and especially being cold and scared at night and you know, it's, it was a very hard thing to cope with as such a young... I was a child, you know? I look at kids now that are fifteen and I think ‘god, they're babies,' you know? I just think it's too young for somebody to deal with that. So yeah, that was my homelessness journey.
</p>
<p>
I think, for me, there was a... I think as a young child growing up in a home where there was a lot of physical abuse, there was a lot of sexual abuse. All that was going on from a very, very young age and I think that there was something inside me that was... It was a survival, it was like survival-mechanism just kicked in and that was what kept me going. There was just something inside me and I don't know where it came from. I don't know, I don't know how I had it and somebody else might not have it, but it was just there and I just kept... I kept... When I was a young child I used to watch television and I would watch these families in these television dramas, you know, and think ‘that's normality'. And I knew it wasn't normal because it was television, but as a young child I just looked at it and thought I knew that what I was living wasn't right or normal, so I would lose myself in television. So I think I was always striving for that perfect Waltons or whatever, you know, the family drama that I'd been watching might have been, you know, type thing. There was... I always say it was stubbornness and... A survival mechanism and stubbornness was what got me through.
</p>
<p>
After my diagnosis, I felt excluded from theatre definitely because my agent - not my last agent, but my agent when I first came to London - we were discussing things one day and I don't know if it was, I don't know if it was when somebody had died of AIDS or... Something had made the question come up in conversation and she said to me, this was before I was positive, that she said to me “Stephen, nobody with HIV or AIDS will ever be a leading man in a West End show here in the UK,” and I think this was about five years before I became positive but that stayed with me, so when I became positive I was working in theatre, I was acting, I was... but I felt so excluded from that community and that space and I knew that there must have been other people but nobody spoke about it. It was 2006 and nobody was speaking about it, so I did, I felt very... I felt... I kept going back to what she had said, I kept thinking ‘I don't have a place in theatre anymore. There's no place for me.' And I think I began to step back from theatre and I definitely felt excluded from my friends as well, I couldn't... I became HIV-positive after a rape. It really makes you step back from everybody because you feel nobody understands what I'm going through and however much people try, they can't get what you have experienced, you know? It was... I really, I felt very excluded . I felt excluded from the whole world. If that makes sense? I just felt as if I didn't have a place, anymore. And it really made me question ‘should I still be here?' I really... I felt that definitely for those first two years I used to think about it, listen to music, you know when I came home at night and just think ‘I don't know if I should be here anymore'. So, from a lot of places I felt excluded.
</p>
<p>
Theatre for me was my world. As a young kid, I'd look to - as I said, I mentioned to you earlier - I looked at these people and idolised what they did and their craft and as I got older I started to learn more and more about it and I wanted to do it as a career but was told “... it's a hobby.” It's not a career, you know? So the careers people told me it's a hobby. When I eventually went to college, trained, left college, came to London, started auditioning and then got my first West End show. It was everything, it was everything. To stand on that stage, you know... There used to be a scene in Bombay Dreams when I would come onto the stage and it would just be in darkness and then there would be a spotlight that would shine down. Now, there would just be me on the stage and I would have this song called ‘Love's Never Easy' and I used to look up at that spotlight and I used to think about my life and what had happened in my life and look at where I was now and I kind of used to pat myself on the back every night, you know, and just go ‘look'. So, theatre for me was everything, you know, and to be excluded from that was devastating, you know, because I thought ‘if I don't have theatre', I didn't know what I had, you know, because that at that age, at that time, I didn't really... I thought... As an actor you're trained to give everything, your life, soul and all your finances, everything goes into being an actor and I was still at that stage in my life, you know, so... I kinda didn't realise then how important friends were. That's something that came as the years went on, so to lose theatre for me was, yeah... Was devastating.
</p>
<p>
When I started to tell people it was awful. It was one of the most awful things that I've ever had to do because I had to tell these people that I cared about, that cared about me, I had to tell them that I'd been raped and then I had to tell them that I was HIV-positive, so it was like being punched twice, you know, it was... And some of them dealt with it and others fell apart and I think back to it now and think ‘god, some people were so dramatic,' but it was really, really unbelievably difficult and some people stayed and some people didn't. You know, I lost friends. I think back to that now and it still makes me sad. I don't think you ever get over losing people because of something that has happened to you, you know like HIV. So yeah... It was, it was a tough time for me and for my friends as well.
</p>
<p>
A negative of being diagnosed would be losing friends and also there was... I had a friend in my life who was a lot older, she was in her... Molly was in her sixties and I never - she's passed away now - but I never told her and it was always that secrecy between me and her. I thought to tell her would have devastated her and I just didn't... I told so many of my other friends and I just thought that I could never tell her, you know. And she died and she never knew... And I'm glad that she never went through having to know, but also when she was here it was hard because I couldn't tell. But, to lose... I lost one of my best friends when I found out I was HIV-positive and it wasn't because she was a bad person or... It was simply because - and she told me, we spoke one night when she'd had a few glasses of wine - she said: “I can't cope with watching you die.” And that was in 2006 and she thought then, you know, that I was going to die and to be honest I thought that as well, you know. For those two years I thought ‘I'm just waiting to die.' So, it wasn't, it wasn't something that I blamed her for but it was, it was unbelievably difficult and it still is to this day, you know, will it occasionally, you know, as the years have gone on, you know, we occasionally text on birthdays or Christmas but I still lost somebody that was a massive, massive part of my life. A massive part of my theatre life as well because that's how I met her, through theatre, so it was, yeah...
</p>
<p>
I suppose a positive out of it is just that I have... I think just that I have found a strength in talking, you know, I think, I think talking about my life is something that has been a massive thing for me and there was so many secrets growing up as a child and the reason I was homeless for six months was because of secrecy. The reason I became homeless was because of secrecy. My adoption was a secret. There was so many secrets, so to break down that wall of secrecy, not only about my life but about HIV as well is actually a really refreshing thing because it's so nice to be able to say “... well, I don't care who knows, I don't care, let them come to me, let them ask me.” Because I would rather people came and asked me questions so that I could give them the correct story, you know? So it's... In that sense, it's very empowering, to be able to go: “Yep, this is me.”
</p>
<p>
My community was always being with people and being part of theatre groups or other acting-related things so that was... That was my being part of things. I suppose now, obviously COVID has affected us all massively. My communities are smaller. I suppose I look at my friends as a community and, you know, I have fewer friends as I've got older but they are good friends and although there's only a few I know that they're there and that I can rely on them. I think as you get older your friends tend to get smaller, but... I suppose I am and I'm not, you know, that's my answer to that question. I kind of feelI've never been... Unless I'm there with people that's my community. I'm not best at being an online-community person or a, you know, so I tend to leave all that to other people.
</p>
<p>
Amongst my DVDs and my two cats and the photographs and all those kind of things that is my safe space I suppose. Outside of that, theatre, you know? To go to a theatre again will be amazing because although I'm in the audience now, I'm not on the stage, it's still... It still does something for me. There's still a fire that gets lit every time I go to the theatre. And a reminder of what I had and the life I had there. And there's also a part of me that thinks, that hopes, that it's not over, you know? Although I've not done it for a couple of years there's definitely a part of me that still feels ‘I would like this to happen again one day.' So, it's... Yeah. I suppose that's a safe space for me as well.
</p>
<p>
I would describe myself as... Sometimes I don't like the word survivor, but I am. You know? And I think you can be a victim and I was a victim for many years of many different things but I'm not a victim any more and that makes me a survivor and I'm a proud survivor. I'm a talkative survivor. I'm a mixture of a lot of different things, but I kind of like most of them, you know? I do like most of them now. It's taken time. It's taken time to get to this point, but, you know, that's how I would describe myself.
</p>
<p>
So, I decided that.. Obviously, my life changed massively seven years ago. I had a transplant and there isn't any room for you to be an actor and be sick, you know. Casting directors don't have time, they're not interested and I knew that I had to create my own community. I had to create my own way of being creative, you know, because the creative juices were still there, however sick I was, you know. So I started a YouTube channel called ‘Hart Talks'. It gives me a space to tell my story, talk about my experiences, my life. But it also really - which is the most exciting thing for me - is it allowed me to open the doors for other people to tell their stories. And that's what I've found I love doing. I love doing interviews with people. I love finding out their stories, finding out what's happened to them in their life, you know. Quite often I'm just left sitting there going ‘wow', by people, because I just think they've had such a life and they have such great stories and yet, I just think there's something in that I've always... Ever since I wrote my one-man show, I said we all have a story and our stories are important and it doesn't matter how big or how small your story is, we all a right to tell it. And if you decide to not tell your story, then that's okay as well. It's just, I just think we're brought up with the ‘don't-tell-anyone, never-tell-anyone' and that nearly killed me.  So... I kind of want to rewrite it and say “... if you want to tell somebody, then my channel will give you that option, to do that. So, yeah.
</p>
`;

module.exports = stephen;
