const florenceStoryLong = require('./florenceStoryLong');

const stories = [
  {
    id: '234sdf',
    title: 'Alan',
    href: 'alan',
    mainImage: 'alan.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Alan's photos",
    longStory: '',
  },
  {
    id: 'fgsdf43',
    title: 'Andy',
    href: 'andy',
    mainImage: 'andy.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Andy's photos",
    longStory: '',
  },
  {
    id: 'xcbxcv32',
    title: 'Anita',
    href: 'anita',
    mainImage: 'anita.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Anita's photos",
    longStory: '',
  },
  {
    id: 'lkj@£2',
    title: 'Ashley',
    href: 'ashley',
    mainImage: 'ashley.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Ashley's photos",
    longStory: '',
  },
  {
    id: 'vsxcx33',
    title: 'Becky',
    href: 'becky',
    mainImage: 'becky.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Becky's photos",
    longStory: '',
  },
  {
    id: 'iou234',
    title: 'Emily',
    href: 'emily',
    mainImage: 'emily.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Emily's photos",
    longStory: '',
  },
  {
    id: '1as4r2',
    title: 'Florence',
    href: 'florence',
    mainImage: 'florence.jpg',
    images: [
      'Florence-privatepictures (1).jpg',
      'Florence-privatepictures (2).jpg',
      'Florence-privatepictures (3).jpg',
      'Florence-privatepictures (4).jpg',
      'Florence-privatepictures (5).jpg',
      'Florence-privatepictures (6).jpg',
      'Florence-privatepictures (7).jpg',
      'Florence-privatepictures (8).jpg',
    ],
    audioFile: '2 Florence Obeda.mp3',
    shortDescription: "Florence's photos",
    longStory: florenceStoryLong,
  },
  {
    id: '121sdf',
    title: 'Harun',
    href: 'harun',
    mainImage: 'harun.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Harun's photos",
    longStory: '',
  },
  {
    id: 'sdfpol1',
    title: 'Jide',
    href: 'jide',
    mainImage: 'jide.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Jide's photos",
    longStory: '',
  },
  {
    id: 'lnl23jdf',
    title: 'John',
    href: 'john',
    mainImage: 'john.jpg',
    images: [],
    audioFile: '',
    shortDescription: "John's photos",
    longStory: '',
  },
  {
    id: '24mlnk',
    title: 'Jonathan',
    href: 'jonathan',
    mainImage: 'jonathan.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Jonathan's photos",
    longStory: '',
  },
  {
    id: 'opipo123',
    title: 'Jose',
    href: 'jose',
    mainImage: 'jose.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Jose's photos",
    longStory: '',
  },
  {
    id: 'po123dsa',
    title: 'Josh',
    href: 'josh',
    mainImage: 'josh.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Josh's photos",
    longStory: '',
  },
  {
    id: 'joshdsasdfa',
    title: 'Joshua',
    href: 'joshua',
    mainImage: 'joshua.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Joshua's photos",
    longStory: '',
  },
  {
    id: 'msdfrew',
    title: 'Martin',
    href: 'martin',
    mainImage: 'martin.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Martin's photos",
    longStory: '',
  },
  {
    id: 'mie9sdxc',
    title: 'Michal',
    href: 'michal',
    mainImage: 'michal.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Michal's photos",
    longStory: '',
  },
  {
    id: 'phisdf32w',
    title: 'Philip',
    href: 'philip',
    mainImage: 'philip.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Philip's photos",
    longStory: '',
  },
  {
    id: 'rah3e21rdfs',
    title: 'Rahim',
    href: 'rahim',
    mainImage: 'rahim.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Rahim's photos",
    longStory: '',
  },
  {
    id: 's89df9',
    title: 'Stephen',
    href: 'stephen',
    mainImage: 'stephen.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Stephen's photos",
    longStory: '',
  },
  {
    id: 'tim213123',
    title: 'Tim',
    href: 'tim',
    mainImage: 'tim.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Tim's photos",
    longStory: '',
  },
  {
    id: 'verbar213sdf',
    title: 'Veritee and Barry',
    href: 'veritee-and-barry',
    mainImage: 'veritee-and-barry.jpg',
    images: [],
    audioFile: '',
    shortDescription: "Veritee and Barry's photos",
    longStory: '',
  },
];

module.exports = stories;
